const ticket = [
  {
    id: "TK001",
    machineId: "MC-101",
    priority: "high",
    status: "open",
    description: "Overheating issue detected",
    createdAt: "11-11-2025",
  },
  {
    id: "TK002",
    machineId: "MC-102",
    priority: "medium",
    status: "in-progress",
    description: "Unusual vibration patterns",
    createdAt: "11-11-2025",
  },
  {
    id: "TK003",
    machineId: "MC-103",
    priority: "low",
    status: "resolved",
    description: "Routine maintenance check",
    createdAt: "11-11-2025",
  },
  {
    id: "TK004",
    machineId: "MC-104",
    priority: "high",
    status: "open",
    description: "Pressure sensor malfunction",
    createdAt: "11-11-2025",
  },
  {
    id: "TK005",
    machineId: "MC-105",
    priority: "medium",
    status: "in-progress",
    description: "Oil level low warning",
    createdAt: "01-11-2025",
  },
  {
    id: "TK001",
    machineId: "MC-101",
    priority: "high",
    status: "open",
    description: "Overheating issue detected",
    createdAt: "10-11-2025",
  },
  {
    id: "TK002",
    machineId: "MC-102",
    priority: "medium",
    status: "in-progress",
    description: "Unusual vibration patterns",
    createdAt: "02-11-2025",
  },
  {
    id: "TK003",
    machineId: "MC-103",
    priority: "low",
    status: "resolved",
    description: "Routine maintenance check",
    createdAt: "03-11-2025",
  },
  {
    id: "TK004",
    machineId: "MC-104",
    priority: "high",
    status: "open",
    description: "Pressure sensor malfunction",
    createdAt: "12-01-2025",
  },
  {
    id: "TK005",
    machineId: "MC-105",
    priority: "medium",
    status: "in-progress",
    description: "Oil level low warning",
    createdAt: "11-01-2024",
  },
  {
    id: "TK001",
    machineId: "MC-101",
    priority: "high",
    status: "open",
    description: "Overheating issue detected",
    createdAt: "15-01-2024",
  },
  {
    id: "TK002",
    machineId: "MC-102",
    priority: "medium",
    status: "in-progress",
    description: "Unusual vibration patterns",
    createdAt: "14-01-2025",
  },
  {
    id: "TK003",
    machineId: "MC-103",
    priority: "low",
    status: "resolved",
    description: "Routine maintenance check",
    createdAt: "13-09-2025",
  },
  {
    id: "TK004",
    machineId: "MC-104",
    priority: "high",
    status: "open",
    description: "Pressure sensor malfunction",
    createdAt: "12-01-2025",
  },
  {
    id: "TK005",
    machineId: "MC-105",
    priority: "medium",
    status: "in-progress",
    description: "Oil level low warning",
    createdAt: "11-10-2025",
  },
];

export default ticket;
